
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: http-frontend
        tier: frontend
    spec:
      containers:
        - name: http-frontend
          image: httpd:latest
          ports:
            - containerPort: 80