// Code generated by go-swagger; DO NOT EDIT.

// Package restapi AjoCard-http-go-server
//
//  Simple Go Api for AjoCard Project
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//  Contact: <shekarau.buba@outlook.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
